AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
